### ISSUE TITLE
Request to include licence

### ISSUE THREAD

**Issue by hb0nd** [ubipo/center-node#1]
Hi! I'm planning to make a plugin that extracts address tags, and was thinking of building it on top of this plugin, however as there's no specified licence it's under copyright by default, I don't know if I'm able to use it. Please could you include a licence?

Many thanks,
Harry :)

**Comment by ubipo** [comment]
Oh heck, didn't see this.

I added GPLv3 now (see: https://josm.openstreetmap.de/wiki/DevelopersGuide/DevelopingPlugins#LegalStuff).
